version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

workflows:
  build:
    jobs:
      - checkout
      - sonarcloud/scan
