version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

      working_directory: ~/QAlenium-Challenges

      environment:
        MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
